// @exposure-buddy/core — pure TypeScript domain logic, zero framework dependencies
// ARC-011: No react-native, expo-*, or @supabase/* imports permitted in this package
export { KV_KEYS, ONBOARDING_STEP_COUNT } from './constants/kvKeys'
export type { AuthTokenProvider } from './interfaces/AuthTokenProvider'
export { emitAccountCreated, onAccountCreated } from './events/accountCreated'
export type { IConsentRecordService } from './services/IConsentRecordService'
export type { ConsentRecord } from './services/ConsentRecord'
export { CONSENT_PURPOSE_ACCOUNT_CREATION, CONSENT_VERSION_CURRENT } from './services/ConsentRecord'
export { ConsentRecordServiceStub } from './stubs/ConsentRecordServiceStub'
export type { IDpoService, PendingDeletionRecord } from './services/IDpoService'
export { DpoServiceStub } from './stubs/DpoServiceStub'
export { detectCrisisKeywords } from './crisis/keywordDetector'
export { CRISIS_KEYWORDS } from './crisis/keywords'
export type { FearLadderItemSummary, FearLadderItem, FearLadderItemStatus } from './selectors/fearLadder'
export { resolveLowestPendingItem } from './selectors/fearLadder'
// ERP session types and state machine (Story 5.2+)
export type { ExposureSession } from './types/exposure-session'
export type { SudsReading } from './types/suds-reading'
export type { SessionRecoveryData } from './types/session-recovery-data'
export type { Result, AppError } from './types/result'
export type { SessionState, SessionEvent } from './erp/session-state-machine'
export { transition } from './erp/session-state-machine'
export { resolveHomeScreenState } from './erp/home-screen-state'
export type { HomeScreenContext, HomeScreenState } from './erp/home-screen-state'
export type { TechniqueType } from './types/technique'
// Calm Me support screen (Story 7.1)
export { CALM_ME_AFFIRMATIONS } from './config/calmMeConfig'
export type { Helpline } from './config/helplines'
export { HELPLINES } from './config/helplines'
// Breathing coach (Story 7.2)
export { BREATHING_GUIDED_CYCLES, BREATHING_TIMER_SECONDS, BREATHING_PATTERN } from './config/breathingCoach'
export type { BreathingPhaseName, AdvancePhaseResult } from './calm-me/breathing-phase'
export { PHASE_ORDER, advancePhase } from './calm-me/breathing-phase'
// 5-4-3-2-1 grounding exercise (Story 7.3)
export { GROUNDING_STEPS, GROUNDING_TOTAL_STEPS } from './config/grounding-exercise'
