// @exposure-buddy/core — pure TypeScript domain logic, zero framework dependencies
// ARC-011: No react-native, expo-*, or @supabase/* imports permitted in this package
export { KV_KEYS, ONBOARDING_STEP_COUNT } from './constants/kvKeys'
export type { AuthTokenProvider } from './interfaces/AuthTokenProvider'
export { emitAccountCreated, onAccountCreated } from './events/accountCreated'
export type { IConsentRecordService } from './services/IConsentRecordService'
export type { ConsentRecord } from './services/ConsentRecord'
export { CONSENT_PURPOSE_ACCOUNT_CREATION, CONSENT_VERSION_CURRENT } from './services/ConsentRecord'
export { ConsentRecordServiceStub } from './stubs/ConsentRecordServiceStub'
export type { IDpoService, PendingDeletionRecord } from './services/IDpoService'
export { DpoServiceStub } from './stubs/DpoServiceStub'
export { detectCrisisKeywords } from './crisis/keywordDetector'
export { CRISIS_KEYWORDS } from './crisis/keywords'
export type { FearLadderItemSummary, FearLadderItem } from './selectors/fearLadder'
export { resolveLowestPendingItem } from './selectors/fearLadder'
// ERP session types and state machine (Story 5.2+)
export type { ExposureSession } from './types/exposure-session'
export type { SudsReading } from './types/suds-reading'
export type { SessionRecoveryData } from './types/session-recovery-data'
export type { Result, AppError } from './types/result'
export type { SessionState, SessionEvent } from './erp/session-state-machine'
export { transition } from './erp/session-state-machine'
export { resolveHomeScreenState } from './erp/home-screen-state'
export type { HomeDisplayState } from './erp/home-screen-state'
